import React from 'react'
import Page from '../components/Page'
import bvp from "../assets/bvpbtech.png"


export default function BvpBtech() {
 
  return (
    <div><Page heading="BVP B.Tech" page="/btech" page2="BVP" overview="Bharati Vidyapeeth, the parent institution has created a landmark in the history of higher education by establishing three institutes in June 1978 and Yashwantrao Mohite College is first of them. The college is accredited with NAAC ‘A’ grade in 2004, Re-accredited with ‘A’ grade in 2011 and for Third cycle in 2017 re-accredited with ‘A+’ grade. At present, the college is one of the constituent units of Bharati Vidyapeeth (Deemed to be University).
    The college offers under graduate and post graduate programmes in various disciplines of Arts, Science, Commerce and Computer Science
    
    The college is recognized Research Centre for Ph.D. degrees in English, Economics, Chemistry, Microbiology, Computer Science, Commerce and Library & Information Science. The special feature of the college is that along with degree courses, the College also conducts two diploma programmes: (1) Diploma in Banking and (2) Diploma in Marketing, which have proved of great help to the students for their placements. In addition, two UGC sponsored Career Oriented Courses in (1) Spoken English (2) Identification and Conservation of Medicinal Plants are introduced for enhancing the employability skills of the students.
    The college promotes national integration by admitting the students from 29 states and has attained international status by accommodating the students from 32 countries. The welfare of the students is always the prime concern of the college. Several activities are organized to support and enhance the capabilities of the students. Publication of the annual number Yashobharati, arranging Cultural Festival ‘Sanskriti’ and conducting National Level General Knowledge Test, as well as organization of National Seminars and workshops every year are some of the features of the college."  image={bvp} course1="B. Tech Biomedical" course2="B. Tech Chemical" course3="B. Tech Civil" course4="B. Tech Computer" course5="B. Tech Electronics and Telecommunications" course6="B. Tech Electrical" course7="B. Tech Electrical" course8="B. Tech Electronics" course9="B. Tech Information Technology" course10="B.Tech Mechanical" eligiblityM1="The Candidate should be an Indian National;" eligiblityM2="Passed HSC or its equivalent examination with Physics and Mathematics as compulsory subjects along with one of the Chemistry or Biotechnology or Biology or Technical Vocational subject or Computer Science or Information Technology or Informatics Practices or Agriculture or Engineering Graphics or Business Studies , and obtained at least 45% marks (at least 40% marks, in case of Backward class categories, Economically Weaker Section and Persons with Disability candidates belonging to Maharashtra State only) in the above subjects taken together and The Candidate should have appeared in all the subjects in MHT-CET 2020 and should obtain non zero score in MHT-CET 2020." eligiblityM3="Passed Diploma in Engineering and Technology and obtained at least 45% marks (at least 40% marks, in case of Backward class categories, Economically Weaker Section and Persons with Disability candidates belonging to Maharashtra State only);
    " eligiblity1="The Candidate should be an Indian National;" eligiblity2="Passed HSC or its equivalent examination with Physics and Mathematics as compulsory subjects along with one of the Chemistry or Biotechnology or Biology or Technical Vocational subject or Computer Science or Information Technology or Informatics Practices or Agriculture or Engineering Graphics or Business Studies and obtained at least 45% marks (at least 40% marks, in case of Backward class categories, Economically Weaker Section and Persons with Disability candidates belonging to Maharashtra State only) in the above subjects taken together and should obtain non zero positive score in JEE Main (B.E/B.Tech) or the candidate should have appeared in all the subjects in MHT-CET 2020 and should obtain non zero score in MHT- CET 2020. However, preference shall be given to the candidate obtaining non zero positive score in JEE Main(B.E/B.Tech) over the candidates who obtained non zero score in MHT-CET 2020."
    eligiblity3=" Passed Diploma in Engineering and Technology and obtained at least 45% marks (at least 40% marks, in case of Backward class categories, economically Weaker Section and Persons with Disability candidates belonging to Maharashtra State only);" nri1=" The candidate should have passed the HSC or its equivalent examination with Physics and Mathematics as compulsory subjects along with one of the Chemistry or Biotechnology or Biology or Technical Vocational subject or Computer Science or Information Technology or Informatics Practices or Agriculture or Engineering Graphics or Business Studies, and obtained at least 45% marks in the above subjects taken together;" nri2="Any other criterion declared from time to time by the appropriate authority as defined under the Act." placement="The highest and average package offered during BVCOE placements 2023 stood at INR 27 LPA and INR 7.8 LPA, respectively. Further, the placement rate recorded during BVCOE placements 2023 was 95%. Apart from this, a total of 65 companies visited the campus during BVCOE placements 2023." company1="Aditya Birla Group." company2="Barclays Technology Centre India (BTCI)" company3="Cognizant." company4="Cybage Software."
    company5="Dell." company6="IBM." company7="Idea Cellular"/></div>
  )
}
