import React from 'react'
import Page from '../components/Page'
import dy from "../assets/dy.jpg"


export default function DyBtech() {
 
  return (
    <div><Page heading="D.Y Patil B.Tech" page="/btech" page2="D.Y Patil" overview="Dr. D. Y. Patil Vidyapeeth (DPU), Pune, sponsored by Dr. D. Y. Patil Vidyapeeth Society, Pune, was declared as “Deemed-to-be-University” under Section 3 of UGC Act 1956 in 2003. From a humble beginning with one constituent unit i.e. Dr. D. Y. Patil Medical College, Hospital and Research Centre, Pune; DPU over the last 16 years has grown exponentially with addition of eight more constituent units under its ambit.
    The Government of India, MHRD, on the advice of UGC, declared Dr. D. Y. Patil Vidyapeeth, Pune as Deemed-to-be University comprising of Dr. D. Y. Patil Medical College, Hospital and Research Centre, Pimpri, Pune vide its notification dated 11th January 2003." overviewL1="Presently,Dr. D. Y. Patil Vidyapeeth, Pune has 13 Constituent Units that has created a brand name “DPU” in the field of Medicine, Dentistry, Nursing, Physiotherapy, Optometry, Biotechnology, Management, Ayurved, Homeopathy, Design, Allied Health Sciences, Liberal Arts, Science & Technology and Online Learning Centre. It has state-of-the-art infrastructure and dedicated faculty members.All the programs offered in these Constituent Units of the Vidyapeeth are duly recognized by the respective Councils such as" overviewL2="Dr. D. Y. Patil Vidyapeeth, Pune has been accredited (3rd Cycle) by NAAC with a CGPA of 3.64 on a four-point scale at ‘A++’ grade on 8th February 2022, valid up to 7th February 2029 . Dr. D. Y. Patil Vidyapeeth, Pune is an 9001: 2015, ISO 14001:2015 and Green Education Campus certified University." overviewL3="The University Grants Commission (UGC) has granted Category-I University status via the UGC letter dated 20 th April 2018 . Subsequently, DPU has been included in the list of Institutions of Deemed to be Universities under section 12B of the UGC Act, 1956." image={dy}  course3="B. Tech Civil" course4="B. Tech Computer"  course7="B. Tech Data Science & Artificial Intelligence"  course9="B. Tech Information Technology" course10="B.Tech Mechanical" eligiblityM1="The Candidate should be an Indian National;" eligiblityM2="Passed HSC or its equivalent examination with Physics and Mathematics as compulsory subjects along with one of the Chemistry or Biotechnology or Biology or Technical Vocational subject or Computer Science or Information Technology or Informatics Practices or Agriculture or Engineering Graphics or Business Studies , and obtained at least 45% marks (at least 40% marks, in case of Backward class categories, Economically Weaker Section and Persons with Disability candidates belonging to Maharashtra State only) in the above subjects taken together and The Candidate should have appeared in all the subjects in MHT-CET 2020 and should obtain non zero score in MHT-CET 2020." eligiblityM3="Passed Diploma in Engineering and Technology and obtained at least 45% marks (at least 40% marks, in case of Backward class categories, Economically Weaker Section and Persons with Disability candidates belonging to Maharashtra State only);
    " eligiblity1="The Candidate should be an Indian National;" eligiblity2="Passed HSC or its equivalent examination with Physics and Mathematics as compulsory subjects along with one of the Chemistry or Biotechnology or Biology or Technical Vocational subject or Computer Science or Information Technology or Informatics Practices or Agriculture or Engineering Graphics or Business Studies and obtained at least 45% marks (at least 40% marks, in case of Backward class categories, Economically Weaker Section and Persons with Disability candidates belonging to Maharashtra State only) in the above subjects taken together and should obtain non zero positive score in JEE Main (B.E/B.Tech) or the candidate should have appeared in all the subjects in MHT-CET 2020 and should obtain non zero score in MHT- CET 2020. However, preference shall be given to the candidate obtaining non zero positive score in JEE Main(B.E/B.Tech) over the candidates who obtained non zero score in MHT-CET 2020."
    eligiblity3=" Passed Diploma in Engineering and Technology and obtained at least 45% marks (at least 40% marks, in case of Backward class categories, economically Weaker Section and Persons with Disability candidates belonging to Maharashtra State only);"  placement="The key highlights of DY Patil College of Engineering BTech and MTech placements 2022 as compared with 2021 are presented in the below-mentioned table: Particulars Placement Statistics (2021) Placement Statistics (2022) Placement rate 84% 86% Companies visited 370 273 the highest package INR 28.39 LPA INR 41.30 LPA Median package INR 4.20 LPA INR 4.80 LPA Note: The placement data of 2022 presented above is updated till Jan 10, 2023." company1="Amazon" company2="Microsoft" company3="D.E Shaw & Co" company4="Nuance"
    company5="ZS Associates" company6="Veritas" company7="RBL"/></div>
  )
}
