import React from 'react'
import Page from '../components/Page'
import jspm from "../assets/jspm.jpg"


export default function JspmBtech() {
 
  return (
    <div><Page heading="JSPM B.Tech" page="/btech" page2="JSPM" overview="JSPM began its humble journey under the visionary leadership of Dr. (Prof.) T. J. Sawant in 2001 with the establishment of Rajarshi Shahu College of Engineering at Tathawade. Today JSPM is an agglomerate of more than 70 Institutes spread across Six campuses providing quality education ranging from Pre-School to Doctoral Research for over 50000+ students in the metropolitan region of Pune and Pimpri-Chinchwad.Armed with the vision of making higher education available and affordable to all those who are desirous of pursuing it, JSPM has in a short span expanded itself into a major education provider across Maharashtra. Along the way JSPM has also acquired two more education trusts The Shetkari Shikshan Mandal and Shri Bhagwant Education and Research Charitable Trust Barshi." overviewL1="JSPM Provides Diploma/ Graduate/ Post-graduate and Research Fellows in Engineering, Management and Pharmacy." overviewL2="Apart from technical education it also established Eight Schools with a combined student strength of 12000+ students across Pune." overviewL3="All schools are affiliated to CBSE." image={jspm} course3="Artificial Intelligence(AI) & Data Science"   course4="B. Tech Computer" course5="B. Tech Electronics and Telecommunications" course6="B. Tech Electrical" course9="B. Tech Information Technology" course10="B.Tech Mechanical" elgilist1="The candidate must pass his/her 10+2 with a 75%." elgilist2="Need to give JEE MAINS" elgilist3="The admission is based on the JEE MAIN rank." elgilist5="Considering the 12th exam results, JEE Main a merit list shall be made category-wise, listing All India Rank (AIR) of candidates." elgilist6="Candidate has to register for counseling online at the official JoSSA website" elgilist7="Candidate ,after registering, need to choose the preferred college, the seat allotment is based on the JEE MAIN score and the preference" elgilist8="Payment of the fee is to be done, then the documents are verified and then the final step is to report to the allotted college with the confirmation letter." placement="Placement Experience: From 6th sem students are getting placed as company visited. 500-600 offers are made and companies visited like..Capgemini, Accenture, Wipro, BYJUS, ATOS, TCS, INFOSYS, TECH MAHINDRA, etc and many more. The highest Package is 18lpa and the average is 6-7lpa. Almost every student like 95% of students is placed. As I get placed in Capgemini after my degree I worked as a software engineer there. Internships Opportunities: Many internships are offered to students according to their skills. some with a stipend and some without. ybi, intel.oasis, etc Projects on which the majority of students work are web development,Html-CSS, web site making, portfolio, data science, cyber security, etc" company1="Amazon" company2="TCS" company3="Cognizant." company4="Cybage Software."
    company5="Dell." company6="IBM." company7="HDFC Bank"/></div>
  )
}