import React from 'react'
import Page from '../components/Page'
import pvg from "../assets/pvg.jpg"
import placementpvg from "../assets/placementpvg.png"

export default function Pvg() {
  return (
    <div><Page heading="PVG B.Tech" page="/btech" page2="PVG College" overview="The parent institute Pune Vidyarthi Griha, formerly known, as Pune Anath Vidyarthi Griha is a well-known charitable institution of Maharashtra, established in 1909, by a group of dedicated and visionary educationists. Last year it has celebrated its centenary too. The Institute conducts a wide spectrum of education programs from Pre-primary to Higher education, in professional fields like Engineering Technology, Management, Computer Science, Commerce & Science College etc." overviewL1="Pune Vidyarthi Griha is 109 years old umbrella having very wide radius of many institutions spread over in Maharashtra at Pune, Nasik, Mumbai, and New Mumbai." overviewL2="Audited Statement 2015-16 Audited Statement 2016-17 Audited Statement 2017-18" overviewL3="EOA Report 2017 Permanent Affiliation Letter SPPU Affiliation Letter 2016-2017" image={pvg}  course4="B. Tech Computer" course5="B. Tech Electronics and Telecommunications"   course9="B. Tech Information Technology" course10="B.Tech Mechanical" course1="Artificial Intelligence and Data Science" course2="B. Tech Printing & Graphic Communication" elgilist1="Pune Vidyarthi Griha’s College of Engineering and Technology (PVG, Pune) offers B.E program in 6 specializations.The admissions are based on MHT-CET conducted by DTE, Maharashtra followed by state level counselling. The Lateral Entry admissions are also conducted by DTE, the candidates have to apply online for Centralized Admission Process (CAP)." elgilist2="The candidates applying for MHT-CET must have passed class 12th examination or equivalent in Science stream with Physics, Chemistry and Mathematics (PCM) as compulsory subjects." elgilist3="The candidates are called for counselling and document verification based on the merit. The candidates are advised to register online for counselling with respect to the college and branch choices within the stipulated time." elgilist4="For Lateral Entry, the candidates should have passed Diploma Course in Engineering or Technology in appropriate branch or B.Sc. degree from a recognized university with Mathematics as the main subject at 10+2 level." placement="" placementimg={placementpvg} company1="TCS" company2="Accenture" company3="Jio"  company5="Wipro" company6="Capgemini" company4="Infosys" 
       /></div>
  )
}
